branches:
  only:
    - master
language: node_js
node_js:
  - stable

before_install:
  - openssl aes-256-cbc -K $encrypted_68227d46cd32_key -iv $encrypted_68227d46cd32_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  # 改变文件权限
  - chmod 600 ~/.ssh/id_rsa
  # 配置 ssh
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  # 配置 git 信息
  - git config --global user.name 'Travis CI'
  - git config --global user.email travis@jimmylv.com
  # 配置 qshell
#  - wget http://devtools.qiniu.com/qshell-v2.0.5.zip
#  - sudo apt-get install unzip
#  - unzip qshell-*.zip
#  - ./qshell_linux_amd64 account $QiNiuAK $QiNiuSK
install:
  - npm install nodeppt -g
script:
  - nodeppt generate ./演讲 ./slides -a
#  - cat ./public/css/base.css # just for verify changes
#  - ./qshell_linux_amd64 qupload scripts/qiniu.conf.json
after_success:
  - |
    cd slides
    touch .nojekyll
    git init
    git add .
    git commit -m "Deploy at `date +"%Y-%m-%d %H:%M"`"
    # Make sure to make the output quiet, or else the API token will leak!
    git push -f -q git@git.coding.net:jimmylv/lecture.git master:master > /dev/null 2>&1
