permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Anya Lin
  email: 
  link: 
  github: 

# 站点信息
title: 林安亚的博客
description: My personal blog
url: 
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/1.png
favicon: /public/img/1.png

# google analytics 设置
ga:
  id: 
  url: 

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
