permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Anya Lin
  email: lay.1010@hotmail.com
  link: http://painterlin.com
  weibo: http://weibo.com/orangeissweet
  github: 

# 站点信息
title: 林安亚的博客
description: My personal blog
url: http://painterlin.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/1.jpg
favicon: /public/img/1.jpg

# google analytics 设置
ga:
  id: 
  url: 

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 科研

# 首页除了最新文章外显示分类
cates: 

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档